version: '3.0'

services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./app:/symfony
    container_name: nginx
    restart: always
    ports:
      - "8081:80"

  php-fpm-8:
    build:
      context: ./php-fpm
    volumes:
      - ./app:/symfony
    container_name: php-fpm-8
    depends_on:
      - mysql

  php-cli:
    build:
      context: ./php-cli
    volumes:
      - ./app:/symfony
    command: sleep 10000
    container_name: php-cli

  mysql:
    image: mysql:5.7
    build:
      context: ./nginx
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./app:/symfony
    container_name: mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=db"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"

volumes:
  mysql: