version: '3.0'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var
    container_name: nginx
    restart: always
    ports:
      - "8081:80"

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/var
    container_name: php-fpm
    depends_on:
      - mysql

  php-cli:
    build:
      context: ./docker/php-cli
    volumes:
      - ./:/var
    command: sleep 10000
    container_name: php-cli

  mysql:
    image: mysql:5.7
    build:
      context: ./docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./:/var
    container_name: mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=db"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
